version: '3'

services:
  backend:
    build: ./backend-example-docker
    restart: always
    ports:
      - 8000:8000
    environment:
      - DB_USERNAME=postgres
      - DB_HOST=db
      - DB_PASSWORD=123
      - FRONT_URL=http://localhost:5000
      - REDIS=redis
  db:
    image: postgres:11.1-alpine
    environment:
      - POSTGRES_PASSWORD=123

  frontend:
    build: ./frontend-example-docker
    environment:
      - API_URL=http://localhost:8000
    ports:
      - 5000:5000

  redis:
    image: redis:5.0.3-alpine
