version: '3'

services:
  backend:
    build: ./backend-example-docker
    restart: always
    ports:
      - 8000:8000
    environment:
      - DB_USERNAME=postgres
      - DB_HOST=db
      - DB_PASSWORD=123
  db:
    image: postgres:11.1-alpine
    environment:
      - POSTGRES_PASSWORD=123
